name: SilverWheelArts
favicon: null
layout_spectrum: 0.2718637373764068
typography_spectrum: 0.6684663866180927
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3550670715048909
  lightness: 0.8573384652845562
  saturation: 0.7633863906376064
  rhythmicContrast: 0.012568332022055984
purpose: []
