analytics: {}
color:
  brandColors:
    - '#c3b6ae'
    - '#90885a'
    - '#767032'
    - '#4f5112'
    - '#4e2b0a'
  brandStrength: 0
  lightness: 0
  rhythmicContrast: 0
  saturation: 0
cta: {}
layout_spectrum: 0.25542
name: SilverWheelArts
opengraph: {}
purpose: []
typography_spectrum: 0.6684663866180927
